Try to use DL, but the performance is still much worse than tree-methods. 

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
DIR = '/content/gdrive/My Drive/Flight_delay/'

In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None) 

file_loc = DIR + 'airline_delay.csv'
#print(file_loc)
data = pd.read_csv(file_loc)
print(data.shape)
data.head(5)

(256285, 21)


year  month carrier            carrier_name airport  \
0  2003      6      AA  American Airlines Inc.     ABQ   
1  2003      6      AA  American Airlines Inc.     ANC   
2  2003      6      AA  American Airlines Inc.     ATL   
3  2003      6      AA  American Airlines Inc.     AUS   
4  2003      6      AA  American Airlines Inc.     BDL   

                                        airport_name  arr_flights  arr_del15  \
0  Albuquerque, NM: Albuquerque International Sun...        307.0       56.0   
1  Anchorage, AK: Ted Stevens Anchorage Internati...         90.0       27.0   
2  Atlanta, GA: Hartsfield-Jackson Atlanta Intern...        752.0      186.0   
3       Austin, TX: Austin - Bergstrom International        842.0      174.0   
4                Hartford, CT: Bradley International        383.0       55.0   

   carrier_ct  weather_ct  nas_ct  security_ct  late_aircraft_ct  \
0       14.68       10.79   19.09         1.48              9.96   
1        7.09        2.00   10.75         0.00              7.16   
2       33.99       27.82  104.76         1.90             17.53   
3       60.24       20.54   47.78         4.69             40.75   
4       14.90        8.91   14.57         0.00             16.61   

   arr_cancelled  arr_diverted  arr_delay  carrier_delay  weather_delay  \
0            1.0           1.0     2530.0          510.0          621.0   
1            0.0           0.0     1390.0          271.0           83.0   
2            5.0           0.0     8314.0         1367.0         1722.0   
3            9.0           1.0     8344.0         3040.0         1032.0   
4            0.0           0.0     3137.0          815.0          574.0   

   nas_delay  security_delay  late_aircraft_delay  
0      676.0            25.0                698.0  
1      581.0             0.0                455.0  
2     3817.0           139.0               1269.0  
3     1835.0           115.0               2322.0  
4      555.0             0.0               1193.0

In [5]:
data.isnull().sum()

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights            362
arr_del15              416
carrier_ct             362
weather_ct             362
nas_ct                 362
security_ct            362
late_aircraft_ct       362
arr_cancelled          362
arr_diverted           362
arr_delay              362
carrier_delay          362
weather_delay          362
nas_delay              362
security_delay         362
late_aircraft_delay    362
dtype: int64

In [0]:
data = data.dropna()

In [10]:
data.isnull().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [11]:
# For Machine Learning

data_ML = data[['year','month','carrier','arr_flights','arr_del15']]
data_ML.groupby(['year','month','carrier','arr_flights']).sum()
print(data_ML.shape)

data_ML['delay_rate'] = data_ML.arr_del15/data_ML.arr_flights
data_ML['year'] = (data_ML.year-2003.)/2019
data_ML['month'] = data_ML.month/12


col         = 'delay_rate'
conditions  = [ data_ML[col] <=0.15, (data_ML[col] >0.15) & (data_ML[col]<= 0.20), 
               (data_ML[col] >0.20) & (data_ML[col]<= 0.25), data_ML[col]> 0.25]
choices     = [0, 1, 2, 3]

data_ML['class'] = np.select(conditions, choices, default=np.nan)
data_ML['class'] = data_ML['class'].astype(int)

data_ML.head(10)

(255869, 5)


year  month carrier  arr_flights  arr_del15  delay_rate  class
0   0.0    0.5      AA        307.0       56.0    0.182410      1
1   0.0    0.5      AA         90.0       27.0    0.300000      3
2   0.0    0.5      AA        752.0      186.0    0.247340      2
3   0.0    0.5      AA        842.0      174.0    0.206651      2
4   0.0    0.5      AA        383.0       55.0    0.143603      0
5   0.0    0.5      AA         89.0       12.0    0.134831      0
6   0.0    0.5      AA        445.0       82.0    0.184270      1
7   0.0    0.5      AA       1266.0      225.0    0.177725      1
8   0.0    0.5      AA        119.0       27.0    0.226891      2
9   0.0    0.5      AA        593.0      101.0    0.170320      1

In [0]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()
data_ML['carrier'] = encoder.fit_transform(data_ML['carrier'])

In [13]:
data_ML.head()

year  month  carrier  arr_flights  arr_del15  delay_rate  class
0   0.0    0.5        1        307.0       56.0    0.182410      1
1   0.0    0.5        1         90.0       27.0    0.300000      3
2   0.0    0.5        1        752.0      186.0    0.247340      2
3   0.0    0.5        1        842.0      174.0    0.206651      2
4   0.0    0.5        1        383.0       55.0    0.143603      0

In [14]:
y = data_ML['class']
X = data_ML.drop(['arr_flights','arr_del15','delay_rate','class'], axis=1)

X.head()

year  month  carrier
0   0.0    0.5        1
1   0.0    0.5        1
2   0.0    0.5        1
3   0.0    0.5        1
4   0.0    0.5        1

In [15]:
print(X.shape)
print(y.shape)

(255869, 3)
(255869,)


In [0]:
X = X.as_matrix()
y = y.as_matrix()

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(204695, 3)
(51174, 3)
(204695,)
(51174,)


In [18]:
from keras.utils.np_utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

Using TensorFlow backend.


In [19]:
print(y_train.shape)
print(y_test.shape)

(204695, 4)
(51174, 4)


In [30]:
from keras import Sequential
from keras.layers import Dense

model = Sequential()

#model.add(Dense(40000,activation='relu',kernel_initializer ='random_normal', input_dim=3))
#model.add(Dense(400,activation='relu',kernel_initializer ='random_normal'))
#model.add(Dense(4,activation='softmax',kernel_initializer = 'random_normal'))

model.add(Dense(40000,activation='relu',input_dim=3))
model.add(Dense(400,activation='relu'))
model.add(Dense(4,activation='softmax'))

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 40000)             160000    
_________________________________________________________________
dense_8 (Dense)              (None, 400)               16000400  
_________________________________________________________________
dense_9 (Dense)              (None, 4)                 1604      
Total params: 16,162,004
Trainable params: 16,162,004
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [38]:
history = model.fit(X_train, y_train, batch_size=30, epochs=10)

Epoch 1/10
204695/204695 [==============================] - 53s 261us/step - loss: 1.2961 - acc: 0.4110
Epoch 2/10
204695/204695 [==============================] - 54s 262us/step - loss: 1.2931 - acc: 0.4145
Epoch 3/10
204695/204695 [==============================] - 54s 263us/step - loss: 1.2903 - acc: 0.4163
Epoch 4/10
204695/204695 [==============================] - 54s 262us/step - loss: 1.2882 - acc: 0.4173
Epoch 5/10
204695/204695 [==============================] - 54s 262us/step - loss: 1.2873 - acc: 0.4191
Epoch 6/10
204695/204695 [==============================] - 54s 262us/step - loss: 1.2858 - acc: 0.4193
Epoch 7/10
204695/204695 [==============================] - 54s 262us/step - loss: 1.2847 - acc: 0.4206
Epoch 8/10
204695/204695 [==============================] - 54s 265us/step - loss: 1.2842 - acc: 0.4210
Epoch 9/10
204695/204695 [==============================] - 54s 264us/step - loss: 1.2829 - acc: 0.4216
Epoch 10/10
204695/204695 [==============================] - 54s

In [0]:
y_pred = model.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix,classification_report

#print(classification_report(y_test,y_pred))
confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))

array([[ 9986,   126,    11,  6144],
       [ 4775,   195,    56,  5842],
       [ 3054,   121,    65,  5898],
       [ 3344,   103,    56, 11398]])

In [41]:
y_pred.argmax(axis=1)

array([3, 0, 1, ..., 3, 0, 0])

## Binary Classification

In [42]:
col         = 'delay_rate'
conditions  = [ data_ML[col] <=0.20, data_ML[col]> 0.20]
choices     = [0, 1]

data_ML['class'] = np.select(conditions, choices, default=np.nan)
data_ML['class'] = data_ML['class'].astype(int)

data_ML.head(10)

year  month  carrier  arr_flights  arr_del15  delay_rate  class
0   0.0    0.5        1        307.0       56.0    0.182410      0
1   0.0    0.5        1         90.0       27.0    0.300000      1
2   0.0    0.5        1        752.0      186.0    0.247340      1
3   0.0    0.5        1        842.0      174.0    0.206651      1
4   0.0    0.5        1        383.0       55.0    0.143603      0
5   0.0    0.5        1         89.0       12.0    0.134831      0
6   0.0    0.5        1        445.0       82.0    0.184270      0
7   0.0    0.5        1       1266.0      225.0    0.177725      0
8   0.0    0.5        1        119.0       27.0    0.226891      1
9   0.0    0.5        1        593.0      101.0    0.170320      0

In [43]:
y = data_ML['class']
X = data_ML.drop(['arr_flights','arr_del15','delay_rate','class'], axis=1)

X.head()

year  month  carrier
0   0.0    0.5        1
1   0.0    0.5        1
2   0.0    0.5        1
3   0.0    0.5        1
4   0.0    0.5        1

In [44]:
y.value_counts()

0    135542
1    120327
Name: class, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(204695, 3)
(51174, 3)
(204695,)
(51174,)


In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [68]:
print(y_train.shape)
print(y_test.shape)

(204695, 2)
(51174, 2)


In [0]:
model = Sequential()

model.add(Dense(40000,activation='relu',input_dim=3))
model.add(Dense(400,activation='relu'))
model.add(Dense(2,activation='sigmoid'))

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [76]:
history = model.fit(X_train, y_train, batch_size=30, epochs=3)

Epoch 1/3
204695/204695 [==============================] - 56s 272us/step - loss: 0.6900 - acc: 0.5353
Epoch 2/3
204695/204695 [==============================] - 55s 268us/step - loss: 0.6866 - acc: 0.5409
Epoch 3/3
204695/204695 [==============================] - 55s 269us/step - loss: 0.6853 - acc: 0.5424


In [77]:
y_pred = model.predict(X_test)
y_pred.argmax(axis=1)

array([0, 0, 0, ..., 0, 0, 0])

In [78]:
confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))

array([[25922,  1152],
       [22413,  1687]])

In [66]:
np.array(y_test)

array([0, 1, 1, ..., 1, 0, 1])

In [57]:
y_pred[y_pred>0.5]

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [73]:
y_pred

array([[0.61691844, 0.37492517],
       [0.5310424 , 0.46796283],
       [0.57587767, 0.42188993],
       ...,
       [0.53927964, 0.45969382],
       [0.7727314 , 0.22943407],
       [0.65941936, 0.34096164]], dtype=float32)

In [80]:
# another try

from keras.layers import Dropout

model = Sequential()

model.add(Dense(40000,activation='relu',input_dim=3))
model.add(Dense(400,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2,activation='sigmoid'))


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [82]:
history = model.fit(X_train, y_train, batch_size=30, epochs=3)

Epoch 1/3
204695/204695 [==============================] - 57s 278us/step - loss: 0.6920 - acc: 0.5301
Epoch 2/3
204695/204695 [==============================] - 56s 276us/step - loss: 0.6916 - acc: 0.5300
Epoch 3/3
204695/204695 [==============================] - 56s 274us/step - loss: 0.6913 - acc: 0.5302


In [83]:
confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))

array([[25922,  1152],
       [22413,  1687]])

In [84]:
history = model.fit(X_train, y_train, batch_size=100, epochs=12)

Epoch 1/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6909 - acc: 0.5305
Epoch 2/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6906 - acc: 0.5305
Epoch 3/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6904 - acc: 0.5305
Epoch 4/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6903 - acc: 0.5305
Epoch 5/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6902 - acc: 0.5309
Epoch 6/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6900 - acc: 0.5318
Epoch 7/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6900 - acc: 0.5325
Epoch 8/12
204695/204695 [==============================] - 21s 101us/step - loss: 0.6898 - acc: 0.5319
Epoch 9/12
204695/204695 [==============================] - 21s 102us/step - loss: 0.6897 - acc: 0.5319
Epoch 10/12
204695/204695 [==============================] - 21s

In [85]:
confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))

array([[25922,  1152],
       [22413,  1687]])

In [0]:
model = Sequential()
model.add(Dense(1024,activation='relu',input_dim=3))
model.add(Dense(512,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(2,activation='sigmoid'))

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [88]:
history = model.fit(X_train, y_train, batch_size=50, epochs=5)

Epoch 1/5
204695/204695 [==============================] - 15s 75us/step - loss: 0.6892 - acc: 0.5379
Epoch 2/5
204695/204695 [==============================] - 14s 70us/step - loss: 0.6856 - acc: 0.5420
Epoch 3/5
204695/204695 [==============================] - 14s 71us/step - loss: 0.6834 - acc: 0.5437
Epoch 4/5
204695/204695 [==============================] - 14s 70us/step - loss: 0.6822 - acc: 0.5445
Epoch 5/5
204695/204695 [==============================] - 15s 71us/step - loss: 0.6816 - acc: 0.5447


In [89]:
confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))

array([[25922,  1152],
       [22413,  1687]])